Name:           ros-kinetic-multi-jackal-control
Version:        0.0.4
Release:        0%{?dist}
Summary:        ROS multi_jackal_control package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/multi_jackal_control
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-controller-manager
Requires:       ros-kinetic-diff-drive-controller
Requires:       ros-kinetic-gazebo-ros-control
Requires:       ros-kinetic-hector-gazebo-plugins
Requires:       ros-kinetic-interactive-marker-twist-server
Requires:       ros-kinetic-joint-state-controller
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-urdf
Requires:       ros-kinetic-xacro
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-controller-manager
BuildRequires:  ros-kinetic-diff-drive-controller
BuildRequires:  ros-kinetic-gazebo-ros-control
BuildRequires:  ros-kinetic-hector-gazebo-plugins
BuildRequires:  ros-kinetic-interactive-marker-twist-server
BuildRequires:  ros-kinetic-joint-state-controller
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-roslaunch
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-urdf
BuildRequires:  ros-kinetic-xacro

%description
Creates the joint and velocity controllers.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Feb 13 2018 Nick Sullivan <nick.dave.sullivan@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Tue Feb 13 2018 Nick Sullivan <nick.dave.sullivan@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Mon Feb 12 2018 Nick Sullivan <nick.dave.sullivan@gmail.com> - 0.0.2-0
- Autogenerated by Bloom

* Wed Feb 07 2018 Nick Sullivan <nick.dave.sullivan@gmail.com> - 0.0.1-0
- Autogenerated by Bloom

